nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: "https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js"
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.8.0/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
